export default {
  API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT, //WHEN YOU EDIT THIS MAKE SURE YOU UPDATE THE URL LOCATIONS FOR THE CALLS //pbtag
  // API_TOKEN: process.env.REACT_APP_API_TOKEN
}